### ISSUE TITLE
I have info about Norway

### ISSUE THREAD

**Issue by RJSchultz** [jduckles/git-collaboration#18]
Because of Norway's high latitude, there are large seasonal variations in daylight. From late May to late July, the sun never completely descends beneath the horizon in areas north of the Arctic Circle (hence Norway's description as the "Land of the Midnight sun"), and the rest of the country experiences up to 20 hours of daylight per day. Conversely, from late November to late January, the sun never rises above the horizon in the north, and daylight hours are very short in the rest of the country.

**Comment by laufers** [comment]
go ahead
